---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
        -X github.com/prometheus/common/version.Version={{ .Version }}
        -X github.com/prometheus/common/version.Revision={{ .Commit }}
        -X github.com/prometheus/common/version.Branch={{ .Branch }}
        -X github.com/prometheus/common/version.BuildUser=Liquescent-Development
        -X github.com/prometheus/common/version.BuildDate={{ .Date }}
        -X github.com/Liquescent-Development/ovn_exporter/pkg/ovn_exporter.appVersion={{ .Version }}
        -X github.com/Liquescent-Development/ovn_exporter/pkg/ovn_exporter.gitBranch={{ .Branch }}
        -X github.com/Liquescent-Development/ovn_exporter/pkg/ovn_exporter.gitCommit={{ .Commit }}
        -X github.com/Liquescent-Development/ovn_exporter/pkg/ovn_exporter.buildUser=Liquescent-Development
        -X github.com/Liquescent-Development/ovn_exporter/pkg/ovn_exporter.buildDate={{ .Date }}
    main: './cmd/ovn_exporter'
    asmflags:
      - 'all=-trimpath='
    gcflags:
      - 'all=-trimpath='
    binary: ovn-exporter
archives:
  - name_template: "ovn-exporter_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
