# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - '"-w -s \
         -X github.com/prometheus/common/version.Version={{ .Version }}\
         -X github.com/prometheus/common/version.Revision={{ .Commit }}\
         -X github.com/prometheus/common/version.Branch={{ .Branch }}\
         -X github.com/prometheus/common/version.BuildUser=greenpau\
         -X github.com/prometheus/common/version.BuildDate={{ .Date }}\
         -X github.com/greenpau/ovn_exporter/pkg/ovn_exporter.appVersion={{ .Version }}\
         -X github.com/greenpau/ovn_exporter/pkg/ovn_exporter.gitBranch={{ .Branch }}\
         -X github.com/greenpau/ovn_exporter/pkg/ovn_exporter.gitCommit={{ .Commit }}\
         -X github.com/greenpau/ovn_exporter/pkg/ovn_exporter.buildUser=greenpau\
         -X github.com/greenpau/ovn_exporter/pkg/ovn_exporter.buildDate={{ .Date }}"'
    main: './cmd/ovn_exporter'
    asmflags:
      - '"all=-trimpath={{.Env.GOPATH}}"'
    gcflags:
      - '"all=-trimpath={{.Env.GOPATH}}"'
    binary: ovn-exporter
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
