name: Release Binaries

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment
      run: |
        set -eu
        cat >> $GITHUB_ENV <<EOF
        GOPATH=$HOME/go
        PATH=$PATH:$HOME/go/bin
        EOF

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: /home/runner/go

    - name: Upload assets
      uses: actions/upload-artifact@v3
      with:
        name: ovn_exporter
        path: dist/*
